# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Material Doc
owner:
  name: Tankery Chen
  link: http://tankery.me
  email: tankery.chen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Material Designed Jekyll template for documentation site. Using structure
  from Jekyll Documentation, and style from Materialize.
baseurl: "/material-doc" # the subpath of your site, e.g. /blog
url: "http://tankery.me" # the base hostname & protocol for your site

collections:
  docs:
    output: true

socials:
  - name: github
    user: tankery
  - name: stackoverflow
    user: 1038900

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
